### ISSUE TITLE
HTML or PDF report

### ISSUE THREAD

**Issue by vChavezB** [HBehrens/puncover#46]
Is it possible to generate a pdf report or an HTML output instead of having to query the localhost server? I want to integrate it into a CI/CD and getting a report would be nice.

If not, which part of the script should I look into to try to implement this feature?

**Comment by vChavezB** [comment]
I retook again this proposal to generate the report to use in a CI/CD env.  I did some basic scripting where I look for all the links in the html, generate the local html website and then fix the links to use the local version. 

So far it works :) I am stil working on using the get requests ?sort=name_desc, stack_asc,etc. Perhaps I cann add a little java script to sort the tables generated from the html.

If  I get to build a useful script to generate the local html I will post updates

**Comment by vChavezB** [comment]
Looks something like this

![grafik](https://user-images.githubusercontent.com/47216966/205520987-b6364a6c-05b1-4fb7-80ea-f29f53daa291.png)

**Comment by vChavezB** [comment]
I will close this issue as I am developing my own script to generate an offline html for this repository.

https://github.com/vChavezB/puncover_html

Regards
Victor

**Comment by HBehrens** [comment]
Thank you, @vChavezB ! This looks like a great bandaid to fix a glaring shortcoming of puncover
