### ISSUE TITLE
Cannot run python because version conflict

### ISSUE THREAD

**Issue by phuongtung0801** [HBehrens/puncover#52]
I have clone this project but I cannot run it because some of package is conflicting version. I'm using venv with python3. I didn't see requirement.txt file in the project so I don't know hove to fix it. Please someone give me some advices.

**Comment by noahp** [comment]
You should now be able to install from PyPi:

`pip install puncover`

https://pypi.org/project/puncover/

Let me know if that helps (and feel free to close the issue if it does)!

**Comment by noahp** [comment]
Closing for now, please reopen if the issue persists!
